sudo: required
language: node_js
node_js:
  - 6
services:
  - docker
before_script:
  - npm i karma -D
  - npm i karma-cli -D
  - npm i karma-qunit -D
  - npm i karma-firefox-launcher -D
  - npm i karma-verbose-reporter -D
  - docker run -v /tmp/data:/data --name "red" -d redis redis-server --appendonly yes
  - docker run -d -p 7379:7379 --link red:redis anapsix/webdis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - karma start --browsers Firefox --single-run
